name: trauxit_task
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  icons_plus: ^4.0.0
  pretty_dio_logger: ^1.3.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
  - assets/
  - assets/lang/
  - assets/fonts/
  - assets/images/
  - assets/icons/
  - assets/images/lottie/
  - assets/icons/svg/
